Repository InfyOmLabs/laravel-generator, pull requests merged in 2020-05, with the labels that each got.

#845 Fix rule validations being populated after they are already required by swagger model doc
  src/Generators/ModelGenerator.php
Labels: under-review

#848 #844 add custom primary key from json file
  src/Generators/ModelGenerator.php
Labels: ready-for-review

#855 #831 add schema namespace in migration
  templates/migration.stub
Labels: ready-for-review

#857 old Vuejs integration removed from 6 version
  src/Commands/Publish/VueJsLayoutPublishCommand.php
  src/Commands/RollbackGeneratorCommand.php
  src/Commands/VueJs/VueJsGeneratorCommand.php
  src/Common/CommandData.php
  src/Generators/VueJs/APIRequestGenerator.php
  src/Generators/VueJs/ControllerGenerator.php
  src/Generators/VueJs/ModelJsConfigGenerator.php
  src/Generators/VueJs/RoutesGenerator.php
  src/Generators/VueJs/TestGenerator.php
  src/Generators/VueJs/ViewGenerator.php
  src/InfyOmGeneratorServiceProvider.php
  templates/vuejs/controller/api_controller.stub
  templates/vuejs/css/vue-styles.css
  templates/vuejs/docs/controller/controller.stub
  templates/vuejs/docs/controller/destroy.stub
  templates/vuejs/docs/controller/index.stub
  templates/vuejs/docs/controller/show.stub
  templates/vuejs/docs/controller/store.stub
  templates/vuejs/docs/controller/update.stub
  templates/vuejs/js/crud.js
  templates/vuejs/js/fields_col.stub
  templates/vuejs/js/fields_row.stub
  templates/vuejs/js/gulpfile.js
  templates/vuejs/js/model-config.stub
  templates/vuejs/js/package.json
  templates/vuejs/request/MyAPIRequest.stub
  templates/vuejs/request/create_request.stub
  templates/vuejs/request/update_request.stub
  templates/vuejs/routes/api_routes.stub
  templates/vuejs/routes/api_routes_base.stub
  templates/vuejs/routes/api_routes_group.stub
  templates/vuejs/routes/routes.stub
  templates/vuejs/test/api_test.stub
  templates/vuejs/vendor/vue-editable/vue-editable.js
  templates/vuejs/vendor/vue-strap/vue-strap.min.js
  templates/vuejs/vendor/vue-table/components/VuetablePaginationMixin.vue
  templates/vuejs/vendor/vue-table/components/VuetablePaginationSimple.vue
Labels: ready-for-review

#859 #853 Support to add Custom model name in select dropdown
  src/Generators/Scaffold/ViewGenerator.php
  src/Generators/ViewServiceProviderGenerator.php
Labels: ready-for-review

#856 Fix decimal fields being generated as floats inside model casts
  src/Common/GeneratorField.php
  src/Generators/ModelGenerator.php
  src/Utils/TableFieldsGenerator.php
Labels: Approved
